sudo: required
services:
  - docker

before_install:
  - docker build -t ehog213/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ehog213/react-test npm test

after_success:
  - docker build -t ehog213/multi-client ./client
  - docker build -t ehog213/multi-nginx ./nginx
  - docker build -t ehog213/multi-server ./server
  - docker build -t ehog213/multi-worker ./worker
  # Log into the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take build images and push them to docker hub
  - docker push ehog213/multi-client
  - docker push ehog213/multi-nginx
  - docker push ehog213/multi-server
  - docker push ehog213/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-622865778154
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY